/*
Copyright Anisur Rahman.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	mycrddevv1 "github.com/anisurrahman75/my-crd/pkg/apis/mycrd.dev/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppsCodes implements AppsCodeInterface
type FakeAppsCodes struct {
	Fake *FakeMycrdV1
	ns   string
}

var appscodesResource = schema.GroupVersionResource{Group: "mycrd.dev", Version: "v1", Resource: "appscodes"}

var appscodesKind = schema.GroupVersionKind{Group: "mycrd.dev", Version: "v1", Kind: "AppsCode"}

// Get takes name of the appsCode, and returns the corresponding appsCode object, and an error if there is any.
func (c *FakeAppsCodes) Get(ctx context.Context, name string, options v1.GetOptions) (result *mycrddevv1.AppsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appscodesResource, c.ns, name), &mycrddevv1.AppsCode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mycrddevv1.AppsCode), err
}

// List takes label and field selectors, and returns the list of AppsCodes that match those selectors.
func (c *FakeAppsCodes) List(ctx context.Context, opts v1.ListOptions) (result *mycrddevv1.AppsCodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appscodesResource, appscodesKind, c.ns, opts), &mycrddevv1.AppsCodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &mycrddevv1.AppsCodeList{ListMeta: obj.(*mycrddevv1.AppsCodeList).ListMeta}
	for _, item := range obj.(*mycrddevv1.AppsCodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appsCodes.
func (c *FakeAppsCodes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appscodesResource, c.ns, opts))

}

// Create takes the representation of a appsCode and creates it.  Returns the server's representation of the appsCode, and an error, if there is any.
func (c *FakeAppsCodes) Create(ctx context.Context, appsCode *mycrddevv1.AppsCode, opts v1.CreateOptions) (result *mycrddevv1.AppsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appscodesResource, c.ns, appsCode), &mycrddevv1.AppsCode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mycrddevv1.AppsCode), err
}

// Update takes the representation of a appsCode and updates it. Returns the server's representation of the appsCode, and an error, if there is any.
func (c *FakeAppsCodes) Update(ctx context.Context, appsCode *mycrddevv1.AppsCode, opts v1.UpdateOptions) (result *mycrddevv1.AppsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appscodesResource, c.ns, appsCode), &mycrddevv1.AppsCode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mycrddevv1.AppsCode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAppsCodes) UpdateStatus(ctx context.Context, appsCode *mycrddevv1.AppsCode, opts v1.UpdateOptions) (*mycrddevv1.AppsCode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(appscodesResource, "status", c.ns, appsCode), &mycrddevv1.AppsCode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mycrddevv1.AppsCode), err
}

// Delete takes name of the appsCode and deletes it. Returns an error if one occurs.
func (c *FakeAppsCodes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(appscodesResource, c.ns, name, opts), &mycrddevv1.AppsCode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppsCodes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appscodesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &mycrddevv1.AppsCodeList{})
	return err
}

// Patch applies the patch and returns the patched appsCode.
func (c *FakeAppsCodes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *mycrddevv1.AppsCode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appscodesResource, c.ns, name, pt, data, subresources...), &mycrddevv1.AppsCode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mycrddevv1.AppsCode), err
}
