/*
Copyright Anisur Rahman.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	mycrddevv1 "github.com/anisurrahman75/my-crd/pkg/apis/mycrd.dev/v1"
	versioned "github.com/anisurrahman75/my-crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/anisurrahman75/my-crd/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/anisurrahman75/my-crd/pkg/client/listers/mycrd.dev/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AppsCodeInformer provides access to a shared informer and lister for
// AppsCodes.
type AppsCodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AppsCodeLister
}

type appsCodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAppsCodeInformer constructs a new informer for AppsCode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAppsCodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAppsCodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAppsCodeInformer constructs a new informer for AppsCode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAppsCodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycrdV1().AppsCodes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycrdV1().AppsCodes(namespace).Watch(context.TODO(), options)
			},
		},
		&mycrddevv1.AppsCode{},
		resyncPeriod,
		indexers,
	)
}

func (f *appsCodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAppsCodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *appsCodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mycrddevv1.AppsCode{}, f.defaultInformer)
}

func (f *appsCodeInformer) Lister() v1.AppsCodeLister {
	return v1.NewAppsCodeLister(f.Informer().GetIndexer())
}
